Direct Exporters - S3 and Blob store
monocle2ai/monocle pull request #41
Opened 2024-09-18 13:20 UTC by sachintendulkar576123

## Proposed changes

This PR updates Direct Exporter to AWS and Azure

- Implemented the AzureBlobSpanExporter() to upload OpenTelemetry traces to Azure Blob Storage.
- Implemented the S3SpanExporter() to export OpenTelemetry traces directly to an AWS S3 bucket.
- Added necessary dependencies for both AWS and Azure support in pyproject.toml
- Instructions for installing AWS S3 and Azure Blob exporters in Monocle_User_Guide.md

## Types of changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [CONTRIBUTING](https://github.com/monocle2ai/monocle/blob/main/CONTRIBUTING.md) doc
- [ ] I have signed the CLA
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2024-09-25 16:09 UTC, oi-raanne requested changes

2024-09-30 07:11 UTC, kshitiz-okahu commented
adding an example with usage of the class would be good

2024-09-30 07:11 UTC, kshitiz-okahu requested changes

2024-09-30 07:11 UTC, kshitiz-okahu commented on src/monocle_apptrace/exporters/azure/azure_exporter.py
> +            if connection_string is None:
You can use 
if not connection_string:

if not container_name:


This checks for empty string as well

2024-10-01 10:23 UTC, oi-raanne requested changes

2024-10-01 10:23 UTC, oi-raanne commented on src/monocle_apptrace/exporters/azure/azure_exporter.py
> +        raise ServiceRequestError(message="Azure Blob Upload Endpoint")
what does the message 'Azure Blob Upload Endpoint` signify ?

2024-10-01 10:23 UTC, oi-raanne commented on src/monocle_apptrace/exporters/azure/azure_exporter.py
> +    def _upload_to_blob_with_retry(self, span_data_batch: str):
`export` method does not support async

2024-10-01 10:29 UTC, oi-raanne requested changes

2024-10-01 10:29 UTC, oi-raanne commented on src/monocle_apptrace/exporters/azure/azure_exporter.py
> +                logger.warning(f"Retry {attempt}/{MAX_RETRIES} failed due to: {str(e)}")
should we retry for any other exception?? We may not need to

2024-10-07 10:13 UTC, oi-raanne requested changes

2024-10-07 10:13 UTC, oi-raanne commented on src/monocle_apptrace/exporters/azure/azure_exporter.py
> +                logger.warning(f"Retry {attempt}/{MAX_RETRIES} failed due to: {str(e)}")
should we retry in `Exception as e:` case ??

2024-10-09 05:54 UTC, oi-raanne requested changes

2024-10-09 05:54 UTC, oi-raanne commented on src/monocle_apptrace/exporters/span_exporter_base.py
> +import time
the name of the file can be just 'base_exporter.py'

2024-10-09 05:54 UTC, oi-raanne commented on src/monocle_apptrace/exporters/azure/azure_exporter.py
> +import os
the name of the this file can be just 'blob_exporter.py' or 'az_blob_exporter.py
'

2024-10-09 05:55 UTC, oi-raanne requested changes

2024-10-09 05:55 UTC, oi-raanne commented on src/monocle_apptrace/exporters/span_exporter_base.py
> +import asyncio
is this used ?

2024-10-09 06:20 UTC, sachintendulkar576123 commented on src/monocle_apptrace/exporters/span_exporter_base.py
> +import asyncio
yes, we are using.

2024-10-09 09:35 UTC, oi-raanne approved these changes

2024-10-14 05:51 UTC, kshitiz-okahu commented
Sync the branch with main

2024-10-14 09:40 UTC, anshul7665 approved these changes

2024-10-14 09:44 UTC, kshitiz-okahu approved these changes

2024-10-14 10:28 UTC, merged