Direct exporter - AWS S3
monocle2ai/monocle pull request #42
Opened 2024-09-24 10:10 UTC by sachintendulkar576123

## Proposed changes

This PR updates Direct Exporter to AWS S3

- Implemented the S3SpanExporter() to export OpenTelemetry traces directly to an AWS S3 bucket.
- Added necessary dependencies for AWS support in pyproject.toml
- Instructions for installing AWS S3 exporters in Monocle_User_Guide.md

## Types of changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [CONTRIBUTING](https://github.com/monocle2ai/monocle/blob/main/CONTRIBUTING.md) doc
- [ ] I have signed the CLA
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2024-10-08 13:22 UTC, Hansrajr requested changes

2024-10-08 13:22 UTC, Hansrajr commented on src/monocle_apptrace/exporters/aws/aws_exporter.py
> +        except self.s3_client.exceptions.NoSuchBucket:
the exception handling to be more specific. distinguish between error codes from ClientError, such as 404, 403, and 400, and  TypeError.

2024-10-09 08:34 UTC, oi-raanne requested changes

2024-10-09 08:34 UTC, oi-raanne commented on src/monocle_apptrace/exporters/aws/aws_exporter.py
> +import os
name can be s3_exporter.py

2024-10-09 09:36 UTC, oi-raanne approved these changes

2024-10-14 05:51 UTC, kshitiz-okahu commented
Sync the branch with main

2024-10-14 09:39 UTC, anshul7665 approved these changes

2024-10-14 09:44 UTC, kshitiz-okahu approved these changes

2024-10-14 10:03 UTC, merged