Add monocle version changes and fix tests
monocle2ai/monocle pull request #64
Opened 2024-10-23 04:08 UTC by kshitiz-okahu

## Proposed changes

Added monocle version in span
Fix tests

## Types of changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [CONTRIBUTING](https://github.com/monocle2ai/monocle/blob/main/CONTRIBUTING.md) doc
- [ ] I have signed the CLA
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2024-10-25 05:39 UTC, kshitiz-okahu commented
add span.type in workflow span

2024-10-28 05:45 UTC, oi-raanne approved these changes

2024-10-28 05:46 UTC, oi-raanne requested changes

2024-10-28 05:46 UTC, oi-raanne commented on .github/workflows/tox.yml
> +    branches: [ "main", "kshitiz/update_test" ]
pls change this

2024-10-28 06:05 UTC, kshitiz-okahu commented on .github/workflows/tox.yml
> +    branches: [ "main", "kshitiz/update_test" ]
yes, just fixing the last failing test

2024-10-28 09:03 UTC, oi-raanne approved these changes

2024-10-30 14:55 UTC, oi-raanne requested changes

2024-10-30 14:55 UTC, oi-raanne commented on src/monocle_apptrace/wrap_common.py
> +                span.set_attribute("monocle_sdk_version",sdk_version)
can the attribute be `monocle_apptrace.version` to reflect the package name

2024-11-14 04:04 UTC, closed without merging