Capturing vectorstore deployment url
monocle2ai/monocle pull request #80
Opened 2024-11-26 10:23 UTC by sachintendulkar576123

## Proposed changes

This PR:

- we are capturing the vector deployment url for OpenSearch vectorstore

## Types of changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [CONTRIBUTING](https://github.com/monocle2ai/monocle/blob/main/CONTRIBUTING.md) doc
- [ ] I have signed the CLA
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2024-11-26 11:05 UTC, oi-raanne requested changes

2024-11-28 04:55 UTC, oi-raanne commented
unit tests missing

2024-11-28 04:56 UTC, oi-raanne requested changes

2024-11-28 04:56 UTC, oi-raanne commented on src/monocle_apptrace/utils.py
> +def get_keys_as_tuple(dictionary, *keys):
```
def get_keys_as_tuple(dictionary, *keys):
    return tuple(dictionary.get(key, None) for key in keys)
```

2024-11-28 04:56 UTC, oi-raanne commented on src/monocle_apptrace/utils.py
> +        host_port_result = f"{host[0]}:{port[0]}" if host or port else None
return host if no port available

2024-11-28 04:56 UTC, oi-raanne commented on src/monocle_apptrace/utils.py
> +            host_port_result = f"{host[0]}:{port[0]}" if host or port else None
return host if no port available

2024-11-28 15:15 UTC, oi-raanne approved these changes

2024-11-28 19:37 UTC, kshitiz-okahu approved these changes

2024-11-29 05:09 UTC, merged